"""Write the Quarto post: index.qmd and widgets/<group>.json.

The .qmd has no code to run: Markdown for the prose, Markdown code blocks for shown code, and raw
HTML blocks for the other outputs. A JSON page model (script#mb-model) holds the default figures,
charts and control specs; the runtime (blog/assets/mb/mb.js) reads it. Plotly templates are stored
once (model.templates) and figures point to them ({"$template": id}).
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path
from urllib.parse import urlparse

import yaml

from .model import Page

RUNTIME = "/assets/mb"  # blog/assets/mb; Quarto makes this path relative to the blog project
GENERATED = "<!-- Generated by scripts/marimo_to_blog.py from notebook.py; source {source}. Do not edit this file: edit notebook.py and run the converter again. -->"


def _json(obj) -> str:
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")


def share_templates(obj, table: dict):
    """Move each layout.template into `table` and leave {"$template": id} in its place."""
    if isinstance(obj, dict):
        out = {}
        for key, value in obj.items():
            if key == "template" and isinstance(value, dict) and ("layout" in value or "data" in value):
                digest = hashlib.sha256(json.dumps(value, sort_keys=True).encode()).hexdigest()[:12]
                table.setdefault(digest, value)
                out[key] = {"$template": digest}
            else:
                out[key] = share_templates(value, table)
        return out
    if isinstance(obj, list):
        return [share_templates(v, table) for v in obj]
    return obj


MIN_SHARED = 16  # number arrays at least this long are stored once when they repeat


def share_arrays(obj) -> tuple[object, dict]:
    """Store each number array that occurs more than once in a table, and leave {"$a": id}."""
    counts: dict[str, int] = {}

    def key(value) -> str | None:
        if (isinstance(value, list) and len(value) >= MIN_SHARED
                and all(isinstance(v, (int, float)) and not isinstance(v, bool) for v in value)):
            return hashlib.sha256(json.dumps(value).encode()).hexdigest()[:12]
        return None

    def count(value):
        k = key(value)
        if k:
            counts[k] = counts.get(k, 0) + 1
        elif isinstance(value, dict):
            for v in value.values():
                count(v)
        elif isinstance(value, list):
            for v in value:
                count(v)

    table: dict[str, list] = {}

    def swap(value):
        k = key(value)
        if k and counts.get(k, 0) > 1:
            table.setdefault(k, value)
            return {"$a": k}
        if isinstance(value, dict):
            return {kk: swap(v) for kk, v in value.items()}
        if isinstance(value, list):
            return [swap(v) for v in value]
        return value

    count(obj)
    return swap(obj), table


def post_markdown(text: str, title: str | None, first: bool) -> str:
    """Blog headings: the post title is the only h1, so the title heading goes and other h1 → h2
    (not in fenced code blocks, where "# " starts a comment)."""
    lines = text.split("\n")
    if first and lines and lines[0].startswith("# ") and title and lines[0][2:].strip() == title.strip():
        lines = lines[1:]
    out, fence = [], None
    for line in lines:
        match = re.match(r"^\s*(`{3,}|~{3,})", line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker[0] * len(marker)
            elif marker.startswith(fence):
                fence = None
        out.append("#" + line if fence is None and re.match(r"^# ", line) else line)
    return "\n".join(out).strip()


def blog_base(post_dir: Path) -> str:
    """The URL path of the blog ("/blog"), from site-url in the Quarto project of the post."""
    config = Path(post_dir).resolve().parent / "_quarto.yml"
    if not config.exists():
        return ""
    site_url = (yaml.safe_load(config.read_text()).get("website") or {}).get("site-url") or ""
    return urlparse(site_url).path.rstrip("/")


def project_links(text: str, base: str) -> str:
    """Links to the site's blog path ("/blog/x/") become Quarto project links ("/x/").

    A notebook links with the full path, which also works in its live notebook. In the Quarto
    project, "/" is the blog folder, and Quarto makes such links relative to the page."""
    if not base:
        return text
    escaped = re.escape(base)
    text = re.sub(rf"\]\({escaped}(/[^)\s]*)", r"](\1", text)
    return re.sub(rf'(\b(?:href|src)=["\']){escaped}(/[^"\']*)', r"\1\2", text)


# Plotly's partial bundles (https://github.com/plotly/plotly.js/blob/master/dist/README.md):
# the page loads the smallest one that has every trace type of its figures.
PLOTLY_BUNDLES = [
    ("basic", {"bar", "pie", "scatter"}),
    ("cartesian", {"bar", "box", "contour", "heatmap", "histogram", "histogram2d", "histogram2dcontour",
                   "image", "pie", "scatter", "scatterternary", "violin"}),
]


def trace_types(obj) -> set[str]:
    """The trace types of every figure in the JSON (a trace without a type is a scatter)."""
    types: set[str] = set()

    def walk(value):
        if isinstance(value, dict):
            for key, v in value.items():
                if key in ("data", "traces") and isinstance(v, list):
                    types.update(t.get("type", "scatter") for t in v if isinstance(t, dict))
                walk(v)
        elif isinstance(value, list):
            for v in value:
                walk(v)

    walk(obj)
    return types


def plotly_bundle(types: set[str]) -> str:
    for name, members in PLOTLY_BUNDLES:
        if types <= members:
            return name
    return "full"


def emit(page: Page, post_dir: Path, front: dict, source: str, plotly_version: str) -> dict:
    """Write the post. Return sizes for the report."""
    post_dir = Path(post_dir)
    widgets = post_dir / "widgets"
    if widgets.exists():
        shutil.rmtree(widgets)
    widgets.mkdir(parents=True)
    templates: dict = {}
    figures_json = [c.rendered.figures for c in page.cells if c.kind == "html" and c.rendered is not None]
    types = trace_types({"figures": figures_json, "groups": page.groups})
    # live: the live notebook (the build exports notebook.py there); controls that the converter
    # could not make interactive link to it
    model = {"version": 1, "source": source, "plotly": plotly_version, "plotlyBundle": plotly_bundle(types),
             "live": "live/", "templates": templates, "cells": {}, "controls": page.controls, "groups": {}}
    sizes = {}
    for cell in page.cells:
        if cell.kind == "html" and cell.rendered is not None:
            model["cells"][str(cell.index)] = share_templates(
                {"figures": cell.rendered.figures, "charts": cell.rendered.charts}, templates)
    for gid, data in page.groups.items():
        shared, arrays = share_arrays(share_templates(data, templates))
        text = _json({**shared, "arrays": arrays})
        (widgets / f"{gid}.json").write_text(text)
        sizes[f"widgets/{gid}.json"] = len(text.encode())
        control_cells = {spec["cell"] for spec in page.controls.values() if spec.get("group") == gid}
        model["groups"][gid] = {"kind": data["kind"], "src": f"widgets/{gid}.json",
                                "cells": sorted(set(data.get("cells", [])) | control_cells)}

    resources = front.get("resources") or []
    resources = [resources] if isinstance(resources, str) else list(resources)
    front = {**front, "resources": [*resources, *(["widgets/*.json"] if "widgets/*.json" not in resources else [])]}
    title = front.get("title")
    base = blog_base(post_dir)
    parts = [GENERATED.format(source=source), "",
             "```{=html}",
             f'<link rel="stylesheet" href="{RUNTIME}/mb.css">',
             f'<script type="module" src="{RUNTIME}/mb.js"></script>',
             f'<script type="application/json" id="mb-model">{_json(model)}</script>',
             "```", ""]
    first_markdown = True
    for cell in page.cells:
        if cell.kind == "markdown" and cell.markdown is not None:
            text = project_links(post_markdown(cell.markdown, title, first_markdown), base)
            first_markdown = False
            if text:
                parts += [text, ""]
        elif cell.kind == "code" and cell.code is not None:
            parts += ["```python", cell.code.rstrip(), "```", ""]
        elif cell.kind == "html" and cell.rendered is not None:
            html = project_links(cell.rendered.html, base)
            parts += ["```{=html}", f'<div class="mb-cell" data-cell="{cell.index}">{html}</div>',
                      "```", ""]
    body = "\n".join(parts)
    qmd = "---\n" + yaml.safe_dump(front, sort_keys=False, allow_unicode=True) + "---\n\n" + body
    (post_dir / "index.qmd").write_text(qmd)
    sizes["index.qmd"] = len(qmd.encode())
    return sizes


def recorded_source(qmd_path: Path) -> str | None:
    """The source hash that a generated index.qmd records (None if the file is not generated)."""
    if not qmd_path.exists():
        return None
    match = re.search(r"Generated by scripts/marimo_to_blog\.py from notebook\.py; source ([0-9a-f]+)\.",
                      qmd_path.read_text())
    return match.group(1) if match else None
